modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "newtons_nonsense"
version = "${version}"
displayName = "Newton's Nonsense"
authors = "TechTastic"
description = '''
A Minecraft physics mod heavily inspired by Valkyrien Skies 2!
'''
#logoFile = ""

[[dependencies.newtons_nonsense]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.newtons_nonsense]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.newtons_nonsense]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "newtons_nonsense.mixins.json"
